version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_api
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:radhe123@host.docker.internal:5432/event_notification
      API_PORT: 8000
    ports:
      - "8000:8000"
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app_network:
    driver: bridge
