"""add_phone_bio_joining_year_to_profiles

Revision ID: 45f1455d1ff2
Revises: dc63a7e496fd
Create Date: 2026-07-12 14:58:20.682618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f1455d1ff2'
down_revision: Union[str, None] = 'dc63a7e496fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty_profiles', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('faculty_profiles', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('faculty_profiles', sa.Column('joining_year', sa.String(length=10), nullable=True))
    op.add_column('student_profiles', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('student_profiles', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('student_profiles', sa.Column('joining_year', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'joining_year')
    op.drop_column('student_profiles', 'bio')
    op.drop_column('student_profiles', 'phone')
    op.drop_column('faculty_profiles', 'joining_year')
    op.drop_column('faculty_profiles', 'bio')
    op.drop_column('faculty_profiles', 'phone')
    # ### end Alembic commands ###
