"""add semester and year to subject

Revision ID: 555c449d8d82
Revises: 45f1455d1ff2
Create Date: 2026-07-17 18:45:07.510897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '555c449d8d82'
down_revision: Union[str, None] = '45f1455d1ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    subject_cols = [c["name"] for c in inspector.get_columns("subjects")]
    if "semester" not in subject_cols:
        op.add_column('subjects', sa.Column('semester', sa.Integer(), nullable=False, server_default='1'))
    if "year" not in subject_cols:
        op.add_column('subjects', sa.Column('year', sa.String(length=10), nullable=False, server_default='FE'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'year')
    op.drop_column('subjects', 'semester')
    # ### end Alembic commands ###
