"""Add session_type to LectureAttendance

Revision ID: d8267280ee15
Revises: daaf10f0721a
Create Date: 2026-07-11 21:53:00.557591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8267280ee15'
down_revision: Union[str, None] = 'daaf10f0721a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_attendances', sa.Column('session_type', sa.String(length=20), nullable=False, server_default="Lecture"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_attendances', 'session_type')
    # ### end Alembic commands ###
