"""Add time_slot

Revision ID: dc63a7e496fd
Revises: d8267280ee15
Create Date: 2026-07-12 11:43:05.126833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc63a7e496fd'
down_revision: Union[str, None] = 'd8267280ee15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_attendances', sa.Column('time_slot', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_attendances', 'time_slot')
    # ### end Alembic commands ###
