"""Add academic_year and semester to LectureAttendance

Revision ID: g9f7h2k3j4l5
Revises: d8267280ee15
Create Date: 2026-07-14 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'g9f7h2k3j4l5'
down_revision: Union[str, None] = '45f1455d1ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_attendances', sa.Column('academic_year', sa.String(length=20), nullable=False, server_default="2026-2027"))
    op.add_column('lecture_attendances', sa.Column('semester', sa.String(length=10), nullable=False, server_default="1"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_attendances', 'semester')
    op.drop_column('lecture_attendances', 'academic_year')
    # ### end Alembic commands ###
