import React from 'react';
import { FileText, Download, Eye, Plus, BarChart2, AlertTriangle, BookOpen, Calendar, Radio } from 'lucide-react';
import './Pages.css';
import './Reports.css';

const Reports = () => {
  const reports = [
    {
      id: 1,
      title: 'Semester Attendance Summary Report',
      description: 'Full class-wise attendance breakdown for Sem V & VI. Includes bar charts and trend lines.',
      icon: <BarChart2 size={24} className="report-icon-color" />,
      date: 'Jul 9, 2025',
      size: '2.4 MB',
      format: 'PDF'
    },
    {
      id: 2,
      title: 'Defaulter List — July 2025',
      description: 'Official auto-generated defaulter list with parent notification status.',
      icon: <AlertTriangle size={24} className="report-icon-color" />,
      date: 'Jul 9, 2025',
      size: '420 KB',
      format: 'PDF'
    },
    {
      id: 3,
      title: 'Faculty Lecture Log — June 2025',
      description: 'Detailed log of lectures conducted by each faculty member with timestamps.',
      icon: <BookOpen size={24} className="report-icon-color" />,
      date: 'Jul 1, 2025',
      size: '1.1 MB',
      format: 'XLSX'
    },
    {
      id: 4,
      title: 'Academic Calendar Events Export',
      description: 'All upcoming events, deadlines, and examination dates parsed from the uploaded PDF.',
      icon: <Calendar size={24} className="report-icon-color" />,
      date: 'Jul 8, 2025',
      size: '38 KB',
      format: 'CSV'
    },
    {
      id: 5,
      title: 'Broadcast Activity Log — Q2 2025',
      description: 'Complete log of all automated notifications sent via Email and Teams.',
      icon: <Radio size={24} className="report-icon-color" />,
      date: 'Jul 7, 2025',
      size: '850 KB',
      format: 'PDF'
    }
  ];

  return (
    <div className="page-container">
      <div className="page-header">
        <h1 className="page-title">Reports & Exports</h1>
        <p className="page-subtitle">Download official department reports generated by the automated agent.</p>
      </div>

      <div className="reports-list">
        {reports.map((report) => (
          <div key={report.id} className="card report-card">
            <div className="report-icon-container">
              {report.icon}
            </div>
            <div className="report-info">
              <h3>{report.title}</h3>
              <p>{report.description}</p>
              <div className="report-meta">
                <span>Generated: {report.date}</span>
                <span className="dot-separator">·</span>
                <span>{report.size}</span>
              </div>
            </div>
            <div className="report-actions">
              <span className="report-format-badge">{report.format}</span>
              <button className="btn btn-outline flex-center" style={{ gap: '0.375rem' }}>
                <Download size={16} /> Download
              </button>
              <button className="btn btn-outline flex-center" style={{ gap: '0.375rem' }}>
                <Eye size={16} /> Preview
              </button>
            </div>
          </div>
        ))}
      </div>

      <div className="custom-report-section">
        <button className="btn btn-text" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--color-primary)', fontWeight: 600, fontSize: '1rem', padding: '1rem 0' }}>
          <Plus size={20} /> Generate Custom Report
        </button>
        <div className="custom-report-header">
          <div style={{ flex: 2, fontWeight: 600, fontSize: '0.75rem', color: 'var(--color-text-secondary)' }}>REPORT TYPE</div>
          <div style={{ flex: 1, fontWeight: 600, fontSize: '0.75rem', color: 'var(--color-text-secondary)' }}>DATE RANGE</div>
          <div style={{ flex: 1, fontWeight: 600, fontSize: '0.75rem', color: 'var(--color-text-secondary)' }}>FORMAT</div>
        </div>
      </div>
    </div>
  );
};

export default Reports;
